services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: "${UID}:${GID}"
    command: -d /config/database.db
    volumes:
      - ./data:/srv
      - ./config:/config
    
    restart: unless-stopped
    networks:
      - toolkit_net
      
networks:
  toolkit_net:
    external: true
    name: toolkit_net